# Generated by Django 4.1.3 on 2022-11-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listencarefree',
            name='audio',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
